[build]
  command = "pip install -r requirements.txt && gcloud auth activate-service-account devfest2023-rsjk@nice-mechanism-378917.iam.gserviceaccount.com --key-file=gcloud_account_key.json && chmod +x rsjk.sh && chmod +x imageToJson.sh && chmod +x runCode.sh && python server.py"
  
  publish = "server.py"

  environment = { PATH = "$PATH:/opt/buildhome/google-cloud-sdk/bin", GOOGLE_APPLICATION_CREDENTIALS = "gcloud_account_key.json" }
